import type { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // ─── MyProtein ───────────────────────────────────────────────────────────
  {
    id: 'mp-001',
    name: 'Impact Whey Protein Chocolate',
    description: 'Proteína de suero de alta calidad con 21g de proteína por porción. Ideal para recuperación muscular post-entrenamiento.',
    price: 34.99,
    image_url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80',
    vendor: 'MyProtein',
    goal: 'muscle_gain',
    category: 'Proteínas',
    unit: '1kg',
    stock: 150,
    rating: 4.8,
    reviews_count: 2341,
  },
  {
    id: 'mp-002',
    name: 'Creatine Monohydrate Unflavored',
    description: 'Creatina monohidratada pura para maximizar la fuerza y potencia en tus sesiones de entrenamiento.',
    price: 18.50,
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&q=80',
    vendor: 'MyProtein',
    goal: 'muscle_gain',
    category: 'Creatina',
    unit: '500g',
    stock: 200,
    rating: 4.9,
    reviews_count: 5129,
  },
  {
    id: 'mp-003',
    name: 'BCAA 4:1:1 Berry Blast',
    description: 'Aminoácidos de cadena ramificada para reducir la fatiga muscular y acelerar la recuperación.',
    price: 22.99,
    image_url: 'https://images.unsplash.com/photo-1559181567-c3190ca9d222?w=400&q=80',
    vendor: 'MyProtein',
    goal: 'endurance',
    category: 'Aminoácidos',
    unit: '400g',
    stock: 80,
    rating: 4.6,
    reviews_count: 987,
  },
  // ─── Optimum Nutrition ───────────────────────────────────────────────────
  {
    id: 'on-001',
    name: 'Gold Standard Whey Double Chocolate',
    description: 'El estándar de oro en proteínas de suero. 24g de proteína, baja en grasa y carbohidratos.',
    price: 54.99,
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    vendor: 'Optimum Nutrition',
    goal: 'muscle_gain',
    category: 'Proteínas',
    unit: '2.27kg',
    stock: 65,
    rating: 4.9,
    reviews_count: 8921,
  },
  {
    id: 'on-002',
    name: 'Gold Standard Pre-Workout',
    description: 'Pre-entreno de alta intensidad con cafeína, beta-alanina y L-citrulina para un rendimiento máximo.',
    price: 39.99,
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&q=80',
    vendor: 'Optimum Nutrition',
    goal: 'endurance',
    category: 'Pre-Entreno',
    unit: '330g',
    stock: 45,
    rating: 4.7,
    reviews_count: 3456,
  },
  {
    id: 'on-003',
    name: 'Serious Mass Weight Gainer',
    description: '1250 calorías por porción. Para quienes buscan ganar masa muscular de forma seria y efectiva.',
    price: 49.99,
    image_url: 'https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400&q=80',
    vendor: 'Optimum Nutrition',
    goal: 'muscle_gain',
    category: 'Gainers',
    unit: '5.44kg',
    stock: 30,
    rating: 4.5,
    reviews_count: 2187,
  },
  // ─── Herbalife ───────────────────────────────────────────────────────────
  {
    id: 'hb-001',
    name: 'Formula 1 Nutritional Shake Vainilla',
    description: 'Batido nutricional equilibrado con proteínas, vitaminas y minerales esenciales para el bienestar diario.',
    price: 45.00,
    image_url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80',
    vendor: 'Herbalife',
    goal: 'wellness',
    category: 'Batidos',
    unit: '550g',
    stock: 120,
    rating: 4.4,
    reviews_count: 4502,
  },
  {
    id: 'hb-002',
    name: 'Total Control Thermogenic',
    description: 'Complemento termogénico con extracto de té verde y cafeína para apoyar el metabolismo.',
    price: 28.50,
    image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&q=80',
    vendor: 'Herbalife',
    goal: 'fat_loss',
    category: 'Termogénicos',
    unit: '90 cápsulas',
    stock: 90,
    rating: 4.3,
    reviews_count: 1876,
  },
  // ─── Garden of Life ──────────────────────────────────────────────────────
  {
    id: 'gol-001',
    name: 'Sport Organic Plant Protein Vanilla',
    description: 'Proteína vegana certificada orgánica. 30g de proteína de guisante, cáñamo y semillas de chía.',
    price: 52.99,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    vendor: 'Garden of Life',
    goal: 'wellness',
    category: 'Proteínas Veganas',
    unit: '806g',
    stock: 55,
    rating: 4.7,
    reviews_count: 1203,
  },
  {
    id: 'gol-002',
    name: 'Vitamin Code Raw Multivitamin',
    description: 'Multivitamínico crudo y entero con probióticos y enzimas. Soporte inmune y de energía.',
    price: 38.00,
    image_url: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80',
    vendor: 'Garden of Life',
    goal: 'wellness',
    category: 'Vitaminas',
    unit: '120 cápsulas',
    stock: 75,
    rating: 4.8,
    reviews_count: 2934,
  },
  // ─── BSN ─────────────────────────────────────────────────────────────────
  {
    id: 'bsn-001',
    name: 'NO-Xplode Pre-Workout Fruit Punch',
    description: 'Pre-entreno legendario con complejo de energía avanzado. Mejora el enfoque y la bomba muscular.',
    price: 36.99,
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
    vendor: 'BSN',
    goal: 'endurance',
    category: 'Pre-Entreno',
    unit: '435g',
    stock: 40,
    rating: 4.6,
    reviews_count: 3211,
  },
  {
    id: 'bsn-002',
    name: 'Syntha-6 Chocolate Milkshake',
    description: 'Matriz de proteínas multi-fase con caseína, suero y albúmina. Liberación sostenida de aminoácidos.',
    price: 42.99,
    image_url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=400&q=80',
    vendor: 'BSN',
    goal: 'muscle_gain',
    category: 'Proteínas',
    unit: '2.27kg',
    stock: 60,
    rating: 4.7,
    reviews_count: 4123,
  },
  // ─── Cellucor ────────────────────────────────────────────────────────────
  {
    id: 'cc-001',
    name: 'C4 Original Pre-Workout Watermelon',
    description: 'El pre-entreno #1 en ventas de América. Energía explosiva, fuerza superior y rendimiento extremo.',
    price: 32.99,
    image_url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&q=80',
    vendor: 'Cellucor',
    goal: 'endurance',
    category: 'Pre-Entreno',
    unit: '390g',
    stock: 95,
    rating: 4.8,
    reviews_count: 9876,
  },
  {
    id: 'cc-002',
    name: 'CLX Fat Burner',
    description: 'Quemador de grasa avanzado con L-carnitina, extracto de té verde y CLA para composición corporal óptima.',
    price: 29.99,
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    vendor: 'Cellucor',
    goal: 'fat_loss',
    category: 'Quemadores',
    unit: '60 cápsulas',
    stock: 70,
    rating: 4.4,
    reviews_count: 2187,
  },
];

export const GOAL_LABELS = [
  { key: 'muscle_gain', label: 'Ganar Músculo', color: 'bg-blue-100 text-blue-700', emoji: '💪' },
  { key: 'fat_loss',    label: 'Perder Grasa',  color: 'bg-orange-100 text-orange-700', emoji: '🔥' },
  { key: 'endurance',   label: 'Resistencia',   color: 'bg-purple-100 text-purple-700', emoji: '⚡' },
  { key: 'wellness',    label: 'Bienestar',      color: 'bg-green-100 text-green-700', emoji: '🌿' },
];

export const VENDORS = [...new Set(MOCK_PRODUCTS.map((p) => p.vendor))];
