import type { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // ── Optimum Nutrition ────────────────────────────────────────────────────
  {
    id: 'on-whey-vanilla',
    name: 'Gold Standard 100% Whey – Vanilla',
    description: 'Proteína de suero de alta calidad, 24g de proteína por porción con aminoácidos esenciales para la recuperación muscular.',
    price: 59.99,
    vendor: 'Optimum Nutrition',
    objective: 'Ganancia Muscular',
    image_url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80',
    unit: '2 lbs / 907g',
    stock: 50,
    tags: ['proteína', 'whey', 'post-entrenamiento'],
  },
  {
    id: 'on-whey-choco',
    name: 'Gold Standard 100% Whey – Chocolate',
    description: 'La fórmula más vendida del mundo, ahora en intenso sabor chocolate, 25g de proteína por scoop.',
    price: 59.99,
    vendor: 'Optimum Nutrition',
    objective: 'Ganancia Muscular',
    image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
    unit: '2 lbs / 907g',
    stock: 45,
    tags: ['proteína', 'whey', 'post-entrenamiento'],
  },
  {
    id: 'on-creatine',
    name: 'Micronized Creatine Monohydrate',
    description: 'Creatina micronizada pura para máxima fuerza y potencia. Sin aditivos ni rellenos.',
    price: 24.99,
    vendor: 'Optimum Nutrition',
    objective: 'Fuerza y Potencia',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    unit: '300g / 60 servicios',
    stock: 80,
    tags: ['creatina', 'fuerza', 'potencia'],
  },
  // ── MyProtein ───────────────────────────────────────────────────────────
  {
    id: 'mp-impact-whey',
    name: 'Impact Whey Protein – Strawberry',
    description: 'Proteína de alta calidad a un precio imbatible, 21g de proteína por porción con bajo contenido en grasa.',
    price: 44.99,
    vendor: 'MyProtein',
    objective: 'Ganancia Muscular',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
    unit: '1 kg / 40 servicios',
    stock: 60,
    tags: ['proteína', 'whey', 'economico'],
  },
  {
    id: 'mp-pre-workout',
    name: 'THE Pre-Workout',
    description: 'Fórmula avanzada pre-entrenamiento con cafeína, beta-alanina y citrulina para máxima energía.',
    price: 34.99,
    vendor: 'MyProtein',
    objective: 'Rendimiento',
    image_url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80',
    unit: '420g / 30 servicios',
    stock: 35,
    tags: ['pre-entreno', 'energía', 'cafeína'],
  },
  {
    id: 'mp-bcaa',
    name: 'Essential BCAA 2:1:1',
    description: 'Aminoácidos ramificados esenciales en proporción 2:1:1 para recuperación muscular y reducción de fatiga.',
    price: 19.99,
    vendor: 'MyProtein',
    objective: 'Recuperación',
    image_url: 'https://images.unsplash.com/photo-1535914254981-b5012eebbd15?w=400&q=80',
    unit: '250g / 50 servicios',
    stock: 70,
    tags: ['bcaa', 'aminoácidos', 'recuperación'],
  },
  // ── Garden of Life ──────────────────────────────────────────────────────
  {
    id: 'gol-sport-protein',
    name: 'Sport Organic Protein – Vanilla',
    description: 'Proteína orgánica certificada USDA, fuente vegana de guisante y semillas de calabaza. Certificada NSF para deporte.',
    price: 49.99,
    vendor: 'Garden of Life',
    objective: 'Nutrición Limpia',
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=80',
    unit: '806g / 20 servicios',
    stock: 25,
    tags: ['vegano', 'orgánico', 'proteína vegetal'],
  },
  {
    id: 'gol-greens',
    name: 'Raw Organic Perfect Food Green Superfood',
    description: '34 superalimentos orgánicos crudos, probióticos y enzimas en una mezcla de polvo verde alcalino.',
    price: 39.99,
    vendor: 'Garden of Life',
    objective: 'Nutrición Limpia',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    unit: '240g / 30 servicios',
    stock: 30,
    tags: ['superfoods', 'vegano', 'orgánico', 'greens'],
  },
  // ── Cellucor ────────────────────────────────────────────────────────────
  {
    id: 'cc-c4-original',
    name: 'C4 Original Pre-Workout – Icy Blue Razz',
    description: 'El pre-entrenamiento más vendido de América, con Explosive Energy Blend y 150mg de cafeína.',
    price: 29.99,
    vendor: 'Cellucor',
    objective: 'Rendimiento',
    image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80',
    unit: '195g / 30 servicios',
    stock: 55,
    tags: ['pre-entreno', 'energía', 'cafeína', 'pump'],
  },
  {
    id: 'cc-c4-ripped',
    name: 'C4 Ripped Pre-Workout',
    description: 'Energía + quema de grasa. Combina la fórmula C4 con L-Carnitina y CLA para definición muscular.',
    price: 34.99,
    vendor: 'Cellucor',
    objective: 'Pérdida de Grasa',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    unit: '200g / 30 servicios',
    stock: 40,
    tags: ['pre-entreno', 'quemagrasa', 'definición'],
  },
  // ── NOW Sports ──────────────────────────────────────────────────────────
  {
    id: 'ns-pea-protein',
    name: 'Pea Protein – Natural Unflavored',
    description: 'Proteína de guisante sin saborizantes ni edulcorantes, 24g de proteína por porción, libre de alérgenos comunes.',
    price: 27.99,
    vendor: 'NOW Sports',
    objective: 'Nutrición Limpia',
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=80',
    unit: '680g / 24 servicios',
    stock: 45,
    tags: ['proteína vegetal', 'sin alérgenos', 'limpio'],
  },
  {
    id: 'ns-omega3',
    name: 'Ultra Omega-3 Fish Oil',
    description: 'Aceite de pescado de alta concentración, 750mg de EPA y 500mg de DHA por softgel para salud cardiovascular.',
    price: 22.99,
    vendor: 'NOW Sports',
    objective: 'Salud General',
    image_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400&q=80',
    unit: '180 softgels',
    stock: 90,
    tags: ['omega-3', 'salud cardiovascular', 'suplemento'],
  },
];

export const OBJECTIVES = [
  'Ganancia Muscular',
  'Pérdida de Grasa',
  'Rendimiento',
  'Recuperación',
  'Nutrición Limpia',
  'Fuerza y Potencia',
  'Salud General',
];

export const VENDORS = [...new Set(MOCK_PRODUCTS.map((p) => p.vendor))];

export const FREQUENCY_OPTIONS: Array<{ value: 1 | 2 | 4; label: string; sublabel: string }> = [
  { value: 1, label: 'Semanal', sublabel: 'Cada 7 días' },
  { value: 2, label: 'Quincenal', sublabel: 'Cada 14 días' },
  { value: 4, label: 'Mensual', sublabel: 'Cada 28 días' },
];
