import type { Product, SubscriptionItem } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // ── Optimum Nutrition ──────────────────────────────────────
  {
    id: 'on-gold-standard',
    name: 'Gold Standard Whey 2lb',
    description: 'Proteína aislada premium con 24g por servicio. La referencia mundial en proteína deportiva.',
    price: 54.99,
    image_url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80',
    vendor: 'Optimum Nutrition',
    category: 'Proteína',
    goal: ['Músculo', 'Recuperación'],
    unit: '2 lb',
    stock: 50,
    is_active: true,
  },
  {
    id: 'on-creatine',
    name: 'Micronized Creatine 300g',
    description: 'Creatina monohidratada micronizada para máxima absorción y fuerza explosiva.',
    price: 24.99,
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80',
    vendor: 'Optimum Nutrition',
    category: 'Creatina',
    goal: ['Fuerza', 'Músculo'],
    unit: '300 g',
    stock: 80,
    is_active: true,
  },
  {
    id: 'on-amino-energy',
    name: 'Amino Energy 65srv',
    description: 'Aminoácidos esenciales con cafeína natural. Pre-entreno y recuperación en uno.',
    price: 34.99,
    image_url: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=400&q=80',
    vendor: 'Optimum Nutrition',
    category: 'Pre-entreno',
    goal: ['Energía', 'Recuperación'],
    unit: '65 servicios',
    stock: 40,
    is_active: true,
  },
  // ── MyProtein ─────────────────────────────────────────────
  {
    id: 'mp-impact-whey',
    name: 'Impact Whey Protein 1kg',
    description: 'Proteína de suero concentrada con excelente relación calidad-precio. 21g de proteína.',
    price: 32.99,
    image_url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&q=80',
    vendor: 'MyProtein',
    category: 'Proteína',
    goal: ['Músculo', 'Definición'],
    unit: '1 kg',
    stock: 100,
    is_active: true,
  },
  {
    id: 'mp-bcaa',
    name: 'BCAA 2:1:1 250g',
    description: 'Aminoácidos de cadena ramificada en proporción óptima 2:1:1 para preservar músculo.',
    price: 18.99,
    image_url: 'https://images.unsplash.com/photo-1544991875-5dc1b05f607d?w=400&q=80',
    vendor: 'MyProtein',
    category: 'Aminoácidos',
    goal: ['Recuperación', 'Definición'],
    unit: '250 g',
    stock: 60,
    is_active: true,
  },
  {
    id: 'mp-clear-whey',
    name: 'Clear Whey Isolate 500g',
    description: 'Proteína aislada estilo bebida refrescante. Sin lactosa, 20g de proteína.',
    price: 42.99,
    image_url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80',
    vendor: 'MyProtein',
    category: 'Proteína',
    goal: ['Definición', 'Bienestar'],
    unit: '500 g',
    stock: 45,
    is_active: true,
  },
  // ── Garden of Life ────────────────────────────────────────
  {
    id: 'gol-protein',
    name: 'Organic Protein Powder',
    description: 'Proteína vegana certificada orgánica. 22g de proteína de origen vegetal, sin OGM.',
    price: 49.99,
    image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=80',
    vendor: 'Garden of Life',
    category: 'Proteína Vegana',
    goal: ['Bienestar', 'Músculo'],
    unit: '680 g',
    stock: 35,
    is_active: true,
  },
  {
    id: 'gol-collagen',
    name: 'Grass Fed Collagen Peptides',
    description: 'Colágeno hidrolizado de res alimentada con pasto. Piel, articulaciones y rendimiento.',
    price: 38.99,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    vendor: 'Garden of Life',
    category: 'Colágeno',
    goal: ['Bienestar', 'Recuperación'],
    unit: '560 g',
    stock: 30,
    is_active: true,
  },
  // ── Cellucor ──────────────────────────────────────────────
  {
    id: 'c4-original',
    name: 'C4 Original Pre-Workout',
    description: 'El pre-entreno más vendido del mundo. 150mg de cafeína, beta-alanina y creatina.',
    price: 39.99,
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
    vendor: 'Cellucor',
    category: 'Pre-entreno',
    goal: ['Energía', 'Fuerza'],
    unit: '60 servicios',
    stock: 55,
    is_active: true,
  },
  {
    id: 'c4-ripped',
    name: 'C4 Ripped Sport',
    description: 'Pre-entreno termogénico para definición. Quema grasa mientras entrenas.',
    price: 44.99,
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    vendor: 'Cellucor',
    category: 'Pre-entreno',
    goal: ['Definición', 'Energía'],
    unit: '60 servicios',
    stock: 40,
    is_active: true,
  },
  // ── NOW Sports ────────────────────────────────────────────
  {
    id: 'now-omega3',
    name: 'Ultra Omega-3 180 cápsulas',
    description: 'Omega-3 de alta concentración EPA/DHA. Salud cardiovascular y anti-inflamatorio.',
    price: 22.99,
    image_url: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80',
    vendor: 'NOW Sports',
    category: 'Vitaminas',
    goal: ['Bienestar', 'Recuperación'],
    unit: '180 cáps',
    stock: 90,
    is_active: true,
  },
  {
    id: 'now-zma',
    name: 'ZMA Sport 90 cápsulas',
    description: 'Zinc, Magnesio y B6 para optimizar la testosterona y la calidad del sueño.',
    price: 19.99,
    image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
    vendor: 'NOW Sports',
    category: 'Vitaminas',
    goal: ['Músculo', 'Bienestar'],
    unit: '90 cáps',
    stock: 70,
    is_active: true,
  },
];

export const MOCK_SUBSCRIPTION_ITEMS: SubscriptionItem[] = [
  {
    id: 'si-1',
    subscription_id: 'sub-1',
    product_id: 'on-gold-standard',
    quantity: 1,
    frequency_weeks: 4,
    next_delivery_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    product: MOCK_PRODUCTS.find((p) => p.id === 'on-gold-standard'),
  },
  {
    id: 'si-2',
    subscription_id: 'sub-1',
    product_id: 'on-creatine',
    quantity: 1,
    frequency_weeks: 2,
    next_delivery_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    product: MOCK_PRODUCTS.find((p) => p.id === 'on-creatine'),
  },
  {
    id: 'si-3',
    subscription_id: 'sub-1',
    product_id: 'mp-bcaa',
    quantity: 2,
    frequency_weeks: 1,
    next_delivery_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active',
    product: MOCK_PRODUCTS.find((p) => p.id === 'mp-bcaa'),
  },
  {
    id: 'si-4',
    subscription_id: 'sub-1',
    product_id: 'now-omega3',
    quantity: 1,
    frequency_weeks: 1,
    next_delivery_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'paused',
    product: MOCK_PRODUCTS.find((p) => p.id === 'now-omega3'),
  },
];

export const ALL_GOALS = ['Músculo', 'Fuerza', 'Definición', 'Energía', 'Recuperación', 'Bienestar'];
export const ALL_VENDORS = [...new Set(MOCK_PRODUCTS.map((p) => p.vendor))];
