import type { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Proteína Whey Gold Standard',
    description: 'Proteína de suero de alta calidad, 24g por porción. Ideal para recuperación muscular post-entreno.',
    price: 59.99,
    image_url: '',
    vendor: 'Optimum Nutrition',
    goal: 'Ganancia muscular',
    unit: '2 lbs',
    stock: 50,
    is_active: true,
  },
  {
    id: '2',
    name: 'Creatina Monohidratada',
    description: 'Creatina pura micronizada. Aumenta fuerza y rendimiento en entrenamientos de alta intensidad.',
    price: 24.99,
    image_url: '',
    vendor: 'Optimum Nutrition',
    goal: 'Ganancia muscular',
    unit: '300g',
    stock: 80,
    is_active: true,
  },
  {
    id: '3',
    name: 'Multivitamínico Sport',
    description: 'Complejo vitamínico completo para atletas activos. Más de 30 nutrientes esenciales.',
    price: 34.99,
    image_url: '',
    vendor: 'Garden of Life',
    goal: 'Bienestar general',
    unit: '90 cáps',
    stock: 120,
    is_active: true,
  },
  {
    id: '4',
    name: 'Colágeno Marino + Vitamina C',
    description: 'Colágeno hidrolizado tipo I y III para articulaciones, piel y recuperación muscular.',
    price: 42.99,
    image_url: '',
    vendor: 'Garden of Life',
    goal: 'Recuperación',
    unit: '200g',
    stock: 60,
    is_active: true,
  },
  {
    id: '5',
    name: 'Pre-Workout C4 Original',
    description: 'Energía explosiva antes del entrenamiento. Con beta-alanina, cafeína y vitaminas B.',
    price: 39.99,
    image_url: '',
    vendor: 'Cellucor',
    goal: 'Energía',
    unit: '390g',
    stock: 45,
    is_active: true,
  },
  {
    id: '6',
    name: 'BCAA 2:1:1 Instantáneo',
    description: 'Aminoácidos de cadena ramificada para reducir la fatiga y acelerar la recuperación.',
    price: 29.99,
    image_url: '',
    vendor: 'NOW Foods',
    goal: 'Recuperación',
    unit: '400g',
    stock: 90,
    is_active: true,
  },
  {
    id: '7',
    name: 'Fat Burner Termogénico',
    description: 'Fórmula termogénica con extracto de té verde, L-carnitina y piperina para quemar grasa.',
    price: 44.99,
    image_url: '',
    vendor: 'Cellucor',
    goal: 'Pérdida de peso',
    unit: '60 cáps',
    stock: 70,
    is_active: true,
  },
  {
    id: '8',
    name: 'Omega-3 Ultra Concentrado',
    description: 'Aceite de pescado de alta concentración EPA/DHA para inflamación y salud cardiovascular.',
    price: 27.99,
    image_url: '',
    vendor: 'NOW Foods',
    goal: 'Bienestar general',
    unit: '90 perlas',
    stock: 100,
    is_active: true,
  },
  {
    id: '9',
    name: 'Proteína Vegana Pea & Rice',
    description: 'Proteína de guisante y arroz integral. 20g por porción. Sin gluten ni lactosa.',
    price: 54.99,
    image_url: '',
    vendor: 'Garden of Life',
    goal: 'Ganancia muscular',
    unit: '1.5 lbs',
    stock: 40,
    is_active: true,
  },
  {
    id: '10',
    name: 'Glucosamina + Condroitina',
    description: 'Soporte articular premium con MSM para mayor movilidad y salud del cartílago.',
    price: 31.99,
    image_url: '',
    vendor: 'NOW Foods',
    goal: 'Recuperación',
    unit: '120 cáps',
    stock: 55,
    is_active: true,
  },
  {
    id: '11',
    name: 'L-Carnitina Líquida 3000',
    description: 'Transporta ácidos grasos a las mitocondrias. Máxima absorción en forma líquida.',
    price: 22.99,
    image_url: '',
    vendor: 'Optimum Nutrition',
    goal: 'Pérdida de peso',
    unit: '465ml',
    stock: 65,
    is_active: true,
  },
  {
    id: '12',
    name: 'Magnesio Bisglicinato 400',
    description: 'Magnesio altamente biodisponible para recuperación muscular, sueño y reducción del estrés.',
    price: 18.99,
    image_url: '',
    vendor: 'NOW Foods',
    goal: 'Bienestar general',
    unit: '120 cáps',
    stock: 130,
    is_active: true,
  },
];

export const VENDORS = [...new Set(MOCK_PRODUCTS.map((p) => p.vendor))];
export const GOALS = [...new Set(MOCK_PRODUCTS.map((p) => p.goal))];
